In [1]:
import numpy as np
import pandas as  pd 
import matplotlib.pyplot as plt
import import_ipynb
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.layers import Dense, Dropout
import keras

Using TensorFlow backend.


In [2]:
import Part1
from Part1 import df


importing Jupyter notebook from Part1.ipynb


In [26]:
class loggingCallback(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.biases = []
        self.w1 = []
        self.w2 = []
        self.w3 = []
        self.weights = []

    def on_epoch_end(self, batch, logs={}):
        #biases in 1. 0 for CYT class
        biases = model.layers[2].get_weights()[1][0]
        #this node to 0 in next layer for CYT Class
        w1 = model.layers[2].get_weights()[0][0][0]
        w2 = model.layers[2].get_weights()[0][1][0]
        w3 = model.layers[2].get_weights()[0][2][0]
        this_weights = model.get_weights()
        self.weights.append(this_weights)
        self.biases.append(biases)
        self.w1.append(w1)
        self.w2.append(w2)
        self.w3.append(w3)
        
my_loggingCallback = loggingCallback()

In [27]:
def model(): 
    model = Sequential([
        Dense(3, activation='sigmoid', input_shape=(8,), name="hidden1", use_bias=True),
        Dense(3, activation='sigmoid', use_bias=True, name="hidden2"),
        Dense(10, activation='sigmoid', use_bias=True, name="output"),
    ])
    sgd = keras.optimizers.SGD(lr=0.01)
    model.compile(
      optimizer=sgd,
      loss='mean_squared_error',
      metrics=['accuracy'],
    )
    return model
model = model()

In [34]:
df_copy = df.drop(["class", "outlier", "outlier2", "outComb"],axis=1)
total = df_copy.values
np.random.shuffle(total)
Y_all = total[:,8]
X_all = total[:,0:8]
Y_all = np.reshape(Y_all, (1484,1))
Y_all = Y_all - 1


In [65]:
my_loggingCallback = loggingCallback()
#Using same model 
history = model.fit(
    x=X_all,
    y=to_categorical(Y_all, num_classes= 10),
    epochs=2,
    batch_size=1,
    validation_split=0,
    validation_data=(X_all,to_categorical(Y_all, num_classes= 10)),
    verbose=.1,
    callbacks=[my_loggingCallback]
)

Train on 1484 samples, validate on 1484 samples
Epoch 1/2
Epoch 2/2


In [66]:
#Training Error
model.evaluate(
  X_all,
  to_categorical(Y_all,num_classes= 10)
)

1484/1484 [==============================] - 0s 45us/step


[0.07777829594769568, 0.31199461221694946]

In [75]:
model.layers[2].get_output_at(0)

<tf.Tensor 'output_1/Sigmoid:0' shape=(None, 10) dtype=float32>

In [81]:
def sigmoid(x, derivative=False):
    val = np.divide(1, 1+np.exp(-x))
    return val

def sigmoid_derivative(x):
    val = x* (1-x)
    return val


In [87]:
fWeights = my_loggingCallback.weights[0]
for i in range(len(fWeights)):
    print(fWeights[i])
    print("======================")

[[ 0.6160523  -0.34510705 -0.5883763 ]
 [-0.29319003 -0.18177587  0.60907865]
 [-0.08259848  0.44190612  0.47213158]
 [ 0.29699922  0.7334618   0.35981753]
 [ 0.4009426   0.29636687  0.3134203 ]
 [ 0.5963915   0.2956808   0.7299677 ]
 [ 0.78103757 -0.53540343 -0.584953  ]
 [ 0.03120595  0.2955624   0.24524157]]
[ 0.2959772   0.16951886 -0.16523151]
[[-0.42060637  1.5417895   1.1542858 ]
 [ 1.0256164   0.52735746  0.95622677]
 [-0.6197083  -0.21812989 -0.02897272]]
[0.21387012 1.0287982  0.2257589 ]
[[-0.6797595   0.09523431  0.17885399 -0.17165105 -0.9313234   0.03920811
  -0.90818894 -0.21169125 -0.5937906  -0.05909228]
 [ 0.40386438 -0.31254143 -0.83598006 -1.1911488  -1.2193332  -1.274206
  -1.0704986  -0.92429745 -1.4152911  -1.4449817 ]
 [-0.5578001  -0.29706824 -0.27637768 -0.19109115 -0.47063872 -1.2301171
  -0.59792686 -0.8559922  -0.4640113  -0.61358416]]
[-0.32856092 -0.41588268 -0.7285214  -0.7550723  -1.1836303  -1.0895857
 -1.4025943  -1.7228734  -1.5208517  -1.7854253 ]


In [116]:
#PART 4

#Layer 1
fWeights[0]
a = np.array(fWeights[0]).reshape(3,8)
at = np.transpose(a)
at.shape

(8, 3)

In [117]:
Layer_1 = sigmoid(np.reshape(np.dot(X_all[0].reshape(1,8),at),[1,3]))

In [118]:
Layer_1

array([[0.4397827 , 0.80995431, 0.61077505]])

In [119]:
#Layer 2
fWeights[0]

array([[ 0.6160523 , -0.34510705, -0.5883763 ],
       [-0.29319003, -0.18177587,  0.60907865],
       [-0.08259848,  0.44190612,  0.47213158],
       [ 0.29699922,  0.7334618 ,  0.35981753],
       [ 0.4009426 ,  0.29636687,  0.3134203 ],
       [ 0.5963915 ,  0.2956808 ,  0.7299677 ],
       [ 0.78103757, -0.53540343, -0.584953  ],
       [ 0.03120595,  0.2955624 ,  0.24524157]], dtype=float32)